{
 "title": "dashboard 001",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "status windows",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Avg. response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "avg(rate(jmeter_rt_summary_sum{code=~\"1.*|2.*|3.*|4.*|5.*\"}[1m])/(rate(jmeter_rt_summary_count{code=~\"1.*|2.*|3.*|4.*|5.*\"}[1m])>0)) by (label)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время отклика quantile",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 3 },
   "targets": [
    { "expr": "jmeter_latency_summary", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "100 - avg(irate(windows_cpu_time_total{job=~\"windows\",instance=~\"localhost:9182\",mode=\"idle\"}[1m]))*100",
     "legendFormat": " cpu"
    }
   ]
  },
  {
   "title": "tps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(jmeter_count_total{label!=\"Transaction Controller start\", code='200'}[$__rate_interval])",
     "legendFormat": "{{code}} {{label}}"
    },
    {
     "expr": "sum(rate(jmeter_count_total{label!=\"Transaction Controller start\", code!=\"Non HTTP response code: org.apache.http.conn.HttpHostConnectException\"}[$__rate_interval]))",
     "legendFormat": "200 HTTP all"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "(rate(jmeter_success_ratio_failure{code!=\"200\"}[1m]))",
     "legendFormat": "{{label}} ..... {{code}} "
    },
    {
     "expr": "sum(rate(jmeter_success_ratio_failure{code!=\"200\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jmeter_threads active",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "jmeter_threads{state=\"active\"}",
     "legendFormat": "{{__name__}}   active"
    }
   ]
  },
  {
   "title": "lumber-room",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overview",
     "type": "table-old",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "windows_os_info{job=~\"windows\"} * on(instance) group_right(product) windows_cs_hostname"
      },
      {
       "expr": "time() - windows_system_system_up_time{job=~\"windows\"}"
      },
      {
       "expr": "windows_cs_logical_processors{job=~\"windows\"} - 0"
      },
      {
       "expr": "avg by (instance) (windows_cpu_core_frequency_mhz{job=~\"windows\"})"
      },
      {
       "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=~\"windows\",mode=\"idle\"}[2m])) * 100)",
       "legendFormat": "CPU test8"
      },
      {
       "expr": "windows_cs_physical_memory_bytes{job=~\"windows\"} - 0"
      },
      {
       "expr": "100 - 100 * windows_os_physical_memory_free_bytes{job=~\"windows\"} / windows_cs_physical_memory_bytes{job=~\"windows\"}",
       "legendFormat": "test8"
      },
      {
       "expr": "1 - (windows_logical_disk_free_bytes{job=~\"windows\",volume=~\"C:\"}/windows_logical_disk_size_bytes{job=~\"windows\",volume=~\"C:\"})"
      },
      {
       "expr": "max by (instance) (1-windows_logical_disk_free_bytes{job=~\"windows\"}/windows_logical_disk_size_bytes{job=~\"windows\"})"
      },
      {
       "expr": "windows_os_processes{job=~\"windows\"}"
      },
      {
       "expr": "sum by (instance) (windows_service_state{job=~\"windows\",state=~\"running\"})"
      }
     ]
    },
    {
     "title": "тпс от сервиса",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{exception=\"None\", uri!=\"/actuator/prometheus\"}[1m])",
       "legendFormat": "{{status}} {{method}}"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{exception=\"None\"}[1m]))",
       "legendFormat": "sum all"
      }
     ]
    },
    {
     "title": "Avg fail",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "(avg(rate(jmeter_success_ratio_failure[1m]))/avg(rate(jmeter_success_ratio_total[1m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Запросов в секунду",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum(rate(jmeter_success_ratio_success[1m]))",
       "legendFormat": "удачных"
      },
      {
       "expr": "sum(rate(jmeter_success_ratio_failure[1m]))",
       "legendFormat": "не удачных"
      },
      {
       "expr": "sum(rate(jmeter_success_ratio_success[5m])) + sum(rate(jmeter_success_ratio_failure[5m]))",
       "legendFormat": "всего"
      }
     ]
    },
    {
     "title": "threads 8080",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      { "expr": "jvm_threads_states_threads", "legendFormat": " {{state}} {{instance}}" }
     ]
    },
    {
     "title": "gc time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum[1m])/rate(jvm_gc_pause_seconds_count[1m])",
       "legendFormat": "{{action}} {{cause}}"
      }
     ]
    },
    {
     "title": "GC count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "delta(jvm_gc_pause_seconds_count[30s])",
       "legendFormat": "{{pod}} {{action}} {{cause}}"
      }
     ]
    },
    {
     "title": "Heap memory neoskils",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area=\"heap\"}",
       "legendFormat": "{{id}}"
      },
      {
       "expr": "jvm_memory_max_bytes{area=\"heap\"}",
       "legendFormat": "max {{id}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100 - avg(irate(windows_cpu_time_total{job=~\"windows\",instance=~\"localhost:9182\",mode=\"idle\"}[1m]))*100",
       "legendFormat": "CPU"
      }
     ]
    },
    {
     "title": "Request per second by HTTPCodesum by (code) ",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 77 },
     "targets": [
      {
       "expr": "rate(jmeter_success_ratio_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request per second by label",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "targets": [
      {
       "expr": "sum(rate(jmeter_success_ratio_total[1m])) by (label)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Success ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
     "targets": [
      {
       "expr": "sum(rate(jmeter_success_ratio_total[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JVM heap - used memory by pool",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
     "targets": [
      {
       "expr": "(jvm_memory_pool_bytes_used{job=\"jmeter\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
     "targets": [
      { "expr": "rate(jmeter_rt_counter[1m])", "legendFormat": "{{quantile}}" }
     ]
    },
    {
     "title": "JVM heap - free memory by pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
     "targets": [
      {
       "expr": "(jvm_memory_pool_bytes_committed {job=~\"jmeter\"}) - (jvm_memory_pool_bytes_used{job=~\"jmeter\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU load",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "sum by (mode) (rate(windows_cpu_time_total{instance=~\"localhost:9182\"}[1m]))",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{mode}} ",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "JVM free memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
     "targets": [
      {
       "expr": "(jvm_memory_bytes_max {job=\"jmeter\"}) - (jvm_memory_bytes_used{job=\"jmeter\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC % time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 119 },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{job=~\"jmeter\"}[1m])",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{job=~\"jmeter\"}[$__interval]) / ignoring(gc) group_left rate(process_cpu_seconds_total{job=~\"jmeter\"}[$__interval])",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{job=~\"jmeter\"}[1m]) / rate(jvm_gc_collection_seconds_count{job=~\"jmeter\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Errors by HTTPCodesum by(code) ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 129 },
     "targets": [
      {
       "expr": "(rate(jmeter_success_ratio_failure[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "OK",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
     "targets": [
      {
       "expr": "sum(jmeter_success_ratio_success) by (label)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Virtual Users vs OK/KOA",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
     "targets": [
      {
       "expr": "sum(rate(jmeter_success_ratio_success[$__interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(jmeter_threads{state=\"active\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(jmeter_success_ratio_failure[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "KO",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
     "targets": [
      {
       "expr": "sum(jmeter_success_ratio_failure) by (label)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Requests vs OK/KOA",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
     "targets": [
      {
       "expr": "(sum(rate(jmeter_success_ratio_success[1m]))/sum(rate(jmeter_success_ratio_total[1m])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum(rate(jmeter_success_ratio_failure[1m]))/sum(rate(jmeter_success_ratio_total[1m])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(jmeter_success_ratio_total[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg. Response Time vs Virtual Users",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
     "targets": [
      {
       "expr": "sum(jmeter_threads{state=\"active\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg((rate(jmeter_rt_summary_sum{code=\"200\"}[$__interval])/(rate(jmeter_rt_summary_count{code=\"200\"}[$__interval])>0)))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg. Response Time vs OK/KOA",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 154 },
     "targets": [
      {
       "expr": "sum(rate(jmeter_success_ratio_success[1m]))",
       "legendFormat": "__auto"
      },
      { "legendFormat": "__auto" },
      {
       "expr": "sum(rate(jmeter_success_ratio_failure[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg success",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
     "targets": [
      {
       "expr": "avg((rate(jmeter_rt_summary_sum{code=\"200\"}[1m])/(rate(jmeter_rt_summary_count{code=\"200\"}[1m])>0)))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pct response times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 162 },
     "targets": [
      {
       "expr": "avg(jmeter_rt_summary{code=\"200\"}) by (quantile)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}